---
title: "Annotation"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

https://jorainer.github.io/MetaboAnnotationTutorials/

```{r start, include = FALSE}
startpoint <- Sys.time()
```


# Libraries

```{r libraries}
p <- "NEG"
software <- "progenesis" #progenesis / mzmine
myfile <- "data/DDA_Profile_NEG_PROG.xlsx" #"data/DDA_Centroid_POS_MZMINE.xlsx" #"data/DDA_Profile_NEG_PROG.xlsx" #"data/DDA_Profile_NEG_MZMINE.xlsx"
#"data/DDA_Centroid_POS_PROG.xlsx"
library(readxl)
library(MetaboAnnotation)
library(ggplot2)
library(RColorBrewer)
library(DT)
library(kableExtra)

myimputer <- function(v){
  set.seed(123)
  if(sum(is.na(v)) == 0) {
    return(v)
  } else {
    napos <- which(is.na(v))
    newval <- runif(length(napos), 0, min(v, na.rm = TRUE)/10)
    out <- v
    out[napos] <- newval
    return(out)
  }
}
```


# Data import

```{r import}
#feat <- read_xlsx(paste0("data/DDA_", p, "_quantificationTable_area.xlsx"))
#feat <- read.csv(paste0("data/DDA_Centroid_", p, "_30ppm_mzmine.csv"), sep = ";") #when reading from mzmine quantification table
#feat <- read.csv(paste0("data/DDA_Centroid_", p, "_PROG.csv"), sep = ";") #when reading from Progenesis quantification table

if(software == "progenesis"){
  feat <- read_xlsx(myfile, skip = 2) #SKIP first two empty rows 

  tmp <- read_xlsx(myfile)
  
  # select normalized data:
  data <- feat[, grep("Normalised", colnames(tmp)):(grep("Raw", colnames(tmp))-1)]

  feat <- data.frame(feat[,c(3, 5)])
  colnames(feat) <- c("mz", "RT")
} else if(software == "mzmine"){
  feat <- read_xlsx(myfile) 
  
  data <- feat[,4:ncol(feat)]
  feat <- data.frame(feat[,c(2, 3)])
  colnames(feat) <- c("mz", "RT")
}
#used with old quantification table from mzmine
#data <- feat[, 4:(ncol(feat)-1)]
#colnames(data) <- gsub("_DDA.*", "", colnames(data))
#colnames(data) <- substr(colnames(data), 11, 1000)
#colnames(data) <- gsub("AK_", "x", colnames(data))

#feat <- data.frame(feat[,3:5]) 
#colnames(feat) <- c("mz", "RT")
feat$FT <- paste0(
  "FT", formatC(seq(nrow(feat)), width = nchar(nrow(feat)), flag = "0"))
rownames(data) <- paste0(
  "FT", formatC(seq(nrow(feat)), width = nchar(nrow(feat)), flag = "0"))

data_t <- data.frame(t(data))
md <- data.frame(
  id = rownames(data_t),
  order = substr(rownames(data_t), 13, 14),
  class = gsub("_.*", "", substr(rownames(data_t), 16, 100))
)

md$class[grepl("D", md$class) & !grepl("O", md$class)] <- "D"
md$class[grepl("DO", md$class)] <- "DO"
md$class[md$class == "PFP"] <- "PF"
md$class[md$class == "PSP"] <- "PS"
md$class <- factor(md$class, levels = c("Blank", "PPB", "QC", "D", "DO", "PF", "PS"))
md$class2 <- md$class
md$class2[md$class2 == "PPB"] <- "Blank"
md$class2 <- droplevels(md$class2)
```


# Feature excluding

## Features not present in study samples

```{r exclude-qc}
mdx <- md[!grepl("P_", md$id) & !md$class2 %in% c("QC", "Blank"),]
mdx$class <- droplevels(mdx$class)
dtx <- data_t[!grepl("P_", md$id) & !md$class2 %in% c("QC", "Blank"),]

dtx[dtx == 0] <- NA
idx <- which(apply(dtx, 2, function(x) sum(is.na(x))) == nrow(dtx))

#feat <- feat[-idx,] #if none of the features is higher in the blank, don't do anything
#data <- data[-idx,]
#data_t <- data_t[,-idx]
 if(length(idx) > 0){
    feat <- feat[-idx,]
data <- data[-idx,]
data_t <- data_t[,-idx]#if indexs is zero don;t do anything
 }
#in the case there ids is not 0 run the code like that
#feat <- feat[-idx,]
#data <- data[-idx,]
#data_t <- data_t[,-idx]
```


## Features present in blank (5-times)

```{r exclude-blank}
group_mean <- aggregate(data_t, list(md$class2), mean)
group_mean <- setNames(data.frame(t(group_mean[,-1])), group_mean[,1])
group_mean$max <- apply(group_mean[,2:6], 1, max)
group_mean$max_class <- apply(group_mean[,2:6], 1, 
                              function(x) colnames(group_mean)[2:6][which.max(x)])
feat <- cbind(feat, group_mean)
idx <- which(group_mean$Blank*5 > group_mean$max)

#feat <- feat[-idx,] #if none of the features is higher in the blank, don't do anything
#data <- data[-idx,]
#data_t <- data_t[,-idx]
 if(length(idx) > 0){
    feat <- feat[-idx,]
data <- data[-idx,]
data_t <- data_t[,-idx]#if indexs is zero don;t do anything
 }
#in the case there ids is not 0 run the code like that
#feat <- feat[-idx,]
#data <- data[-idx,]
#data_t <- data_t[,-idx]

```


# Do some statistics

```{r stats}
data_t[data_t == 0] <- NA
data_t <- apply(data_t, 2, myimputer)
dtx <- data_t[rownames(data_t) %in% mdx$id,]

#feat$pvals <- apply(dtx, 2, function(x) kruskal.test(x, mdx$class)$p.value)
feat$pvals <- apply(dtx, 2, function(x) summary(aov(log10(x)~mdx$class))[[1]][1,"Pr(>F)"])

feat$comparison <- NA
for(i in seq(nrow(feat))){
  if(is.na(feat$pvals[i]) | feat$pvals[i] > 0.05){
    feat$comparison[i] <- "NS"
  } else {
    group_mean <- aggregate(dtx[,i], list(mdx$class), mean)
    group_mean$letter <- NA
    
    tmp_md <- aov(log10(dtx[,i])~mdx$class)
    tmp_tuckey <- data.frame(TukeyHSD(tmp_md)[[1]])
    
    #dunntest <- data.frame(FSA::dunnTest(dtx[,i]~as.factor(mdx$class))$res)
    mylet <- letters[1:4]
    jmylet <- 1
    for(j in seq(nrow(group_mean))){
      k <- order(group_mean$x, decreasing = T)[j]
      if(is.na(group_mean$letter[k])){
        group_mean$letter[k] <- mylet[jmylet]
        jidx <- which(unlist(
          lapply(strsplit(rownames(tmp_tuckey), "-"), 
                 function(x) group_mean$Group.1[k] %in% x)) & 
            tmp_tuckey$p.adj > 0.05)
        if(length(jidx) > 0){
          jidx <- which(group_mean$Group.1 %in% 
                          gsub(paste0("-", group_mean$Group.1[k]), "", 
                               gsub(paste0(group_mean$Group.1[k], "-"), "", 
                                    rownames(tmp_tuckey)[jidx])))
          jidx1 <- which(is.na(group_mean$letter[jidx]))
          jidx2 <- which(!is.na(group_mean$letter[jidx]))
          if(length(jidx1) > 0){
            group_mean$letter[jidx[jidx1]] <- mylet[jmylet]
          }
          if(length(jidx2) > 0){
            group_mean$letter[jidx[jidx2]] <- paste0(group_mean$letter[jidx[jidx2]], 
                                                     mylet[jmylet])
          }
        }
        jmylet <- jmylet + 1
      }
    }
    feat$comparison[i] <- paste(group_mean$letter, collapse = "_") 
  } 
}
feat$comp <- feat$comparison
feat$comp[feat$comp == "a_a_a_a"] <- "NS"
feat$comp[feat$comp == "a_a_a_b"] <- "(D & DO & PF) > PS"
feat$comp[feat$comp == "a_a_ab_b"] <- "(D & DO) > PS"
feat$comp[feat$comp == "a_a_b_a"] <- "(D & DO & PS) > PF"
feat$comp[feat$comp == "a_a_b_ab"] <- "(D & DO) > PF"
feat$comp[feat$comp == "a_a_b_b"] <- "(D & DO) > (PF & PS)"
feat$comp[feat$comp == "a_ab_a_b"] <- "(D & PF) > PS"
feat$comp[feat$comp == "a_ab_ab_b"] <- "D > PS"
feat$comp[feat$comp == "a_ab_b_ab"] <- "D > PF"
feat$comp[feat$comp == "a_ab_b_b"] <- "D > (PF & PS)"
feat$comp[feat$comp == "ab_a_a_b"] <- "(DO & PF) > PS"
feat$comp[feat$comp == "ab_a_ab_b"] <- "DO > PS"
feat$comp[feat$comp == "ab_a_b_a"] <- "(DO & PS) > PF"
feat$comp[feat$comp == "ab_a_b_ab"] <- "DO > PF"
feat$comp[feat$comp == "ab_a_b_b"] <- "DO > (PF & PS)"
feat$comp[feat$comp == "ab_ab_a_b"] <- "PF > PS"
feat$comp[feat$comp == "ab_ab_b_a"] <- "PS > PF"
feat$comp[feat$comp == "ab_b_a_a"] <- "(PF & PS) > DO"
feat$comp[feat$comp == "ab_b_a_b"] <- "PF > (DO & PS)"
feat$comp[feat$comp == "ab_b_ab_a"] <- "PS > DO"
feat$comp[feat$comp == "ab_b_b_a"] <- "PS > (DO & PF)"
feat$comp[feat$comp == "b_a_b_b"] <- "DO > (PF & PS)"
feat$comp[feat$comp == "b_ab_a_ab"] <- "PF > D"
feat$comp[feat$comp == "b_ab_a_b"] <- "PF > (D & PS)"
feat$comp[feat$comp == "b_ab_ab_a"] <- "PS > D"
feat$comp[feat$comp == "b_ab_b_a"] <- "PS > (D & PF)"
feat$comp[feat$comp == "b_b_a_ab"] <- "PF > (D & DO)"
feat$comp[feat$comp == "b_b_a_b"] <- "PF > (D & DO & PS)"
feat$comp[feat$comp == "b_b_ab_a"] <- "PS > (D & DO)"
feat$comp[feat$comp == "b_b_b_a"] <- "PS > (D & DO & PF)"
feat$comp[feat$comp == "ab_b_a_ab"] <- "PF > DO"
feat$comp[feat$comp == "b_a_ab_a"] <- "(DO & PS) > D"
feat$comp[feat$comp == "b_a_ab_ab"] <- "DO > D"
feat$comp[feat$comp == "b_ab_a_a"] <- "(PF & PS) > D"
feat$comp[feat$comp == "b_ab_a_c"] <- "PF > D > PS"
feat$comp[feat$comp == "b_b_a_a"] <- "(PF & PS) > (D & DO)"
feat$comp[feat$comp == "bc_b_a_c"] <- "PF > DO > PS"
feat$comp[feat$comp == "bc_b_c_a"] <- "PS > DO > PF"
feat$comp[feat$comp == "bc_c_b_a"] <- "PS > PF > DO"
feat$comp[feat$comp == "c_b_a_a"] <- "(PF & PS) > DO > D"
feat$comp[feat$comp == "c_b_a_ab"] <- "PF > DO > D"
feat$comp[feat$comp == "c_b_a_c"] <- "PF > DO > D & PS"
feat$comp[feat$comp == "c_b_ab_a"] <- "PS > DO > D"
feat$comp[feat$comp == "c_c_b_a"] <- "PS > PF > (D & DO)"
feat$comp[feat$comp == "a_a_b_c"] <- "(D & DO) > PF > PS"
feat$comp[feat$comp == "a_ab_b_a"] <- "(D & PS) > PF"
feat$comp[feat$comp == "a_b_ab_ab"] <- "D > DO"
feat$comp[feat$comp == "a_b_ab_b"] <- "D > (DO & PS)"
feat$comp[feat$comp == "a_b_b_b"] <- "D > (DO & PF & PS)"
feat$comp[feat$comp == "ab_a_b_c"] <- "DO > PF > PS"
feat$comp[feat$comp == "ab_a_c_b"] <- "DO > PS > PF"
feat$comp[feat$comp == "b_a_a_a"] <- "(DO & PF & PS) > D"
feat$comp[feat$comp == "b_a_a_ab"] <- "(DO & PF) > D"
feat$comp[feat$comp == "b_a_a_b"] <- "(DO & PF) > (D & PS)"
feat$comp[feat$comp == "b_a_a_c"] <- "(DO & PF) > D > PS"
feat$comp[feat$comp == "b_a_ab_b"] <- "DO > (D & PF)"
feat$comp[feat$comp == "b_a_ab_c"] <- "DO > D > PS"
feat$comp[feat$comp == "b_a_b_a"] <- "(DO & PS) > (D & PF)"
feat$comp[feat$comp == "b_a_c_c"] <- "DO > D > (PF & PS)"
feat$comp[feat$comp == "b_ab_c_a"] <- "PS > D > PF"
feat$comp[feat$comp == "b_b_c_a"] <- "PS > (D & DO) > PF"
feat$comp[feat$comp == "b_bc_c_a"] <- "PS > D > PF"
feat$comp[feat$comp == "b_c_bc_a"] <- "PS > D > DO"
feat$comp[feat$comp == "c_b_bc_a"] <- "PS > DO > D"
feat$comp[feat$comp == "c_b_c_a"] <- "PS > DO > (D & PF)"
feat$comp[feat$comp == "c_bc_b_a"] <- "PS > PF > D"

feat$comp[feat$comp == "b_b_a_c"] <- "PF > (D & DO) > PS"
feat$comp[feat$comp == "a_ab_b_c"] <- "D > PF > PS"
feat$comp[feat$comp == "b_bc_a_c"] <- "PF > D > PS"
feat$comp[feat$comp == "b_a_b_ab"] <- "DO > (D & PF)"
feat$comp[feat$comp == "c_b_b_a"] <- "PS > (DO & PF) > D"
feat$comp[feat$comp == "bc_c_a_b"] <- "PF > PS > DO"
feat$comp[feat$comp == "c_bc_a_b"] <- "PF > PS > D"
feat$comp[feat$comp == "ab_b_a_c"] <- "PF > DO > PS"
feat$comp[feat$comp == "b_a_b_c"] <- "DO > (D & PF) > PS"

feat$comp[feat$comp == "c_c_a_b"] <- "PF > PS > (D & DO)"
feat$comp[feat$comp == "c_b_a_b"] <- "PF > (DO & PS) > D"
feat$comp[feat$comp == "a_b_a_b"] <- "(D & PF) > DO & PS)"
feat$comp[feat$comp == "a_b_a_ab"] <- "(D & PF) > DO"
feat$comp[feat$comp == "b_a_c_bc"] <- "DO > D > PF"
feat$comp[feat$comp == "a_a_c_b"] <- "(D & DO) > PS > PF"
feat$comp[feat$comp == "a_b_a_a"] <- "(D & PF & PS) > DO"
feat$comp[feat$comp == "b_c_a_b"] <- "PF > (D & PS) > DO"
feat$comp[feat$comp == "b_a_c_b"] <- "DO > (D & PS) > PF"


levels(factor(feat$comp[grep("_", feat$comp)])) ## TO FINISH!!!!!!

feat$comp <- factor(feat$comp, levels = unique(c("NS", 
                                                 "PS > (D & DO & PF)",
                                                 "PF > (D & DO & PS)",
                                                 "(D & DO) > (PF & PS)", 
                                                 levels(as.factor(feat$comp))))) #the order of classes, the rest is                                                   order alphabetically
feat$classification <- "x"
feat$classification[feat$comp == "NS"] <- "NS"
feat$classification[feat$comp %in% c("PS > (D & DO & PF)",
                                       "PS > (D & DO)", "PS > (D & PF)", 
                                       "PS > (DO & PF)", "PS > D",
                                       "PS > DO", "PS > PF", "PS > DO > PF",
                                       "PS > DO > D", "PS > PF > DO", "PS > PF > (D & DO)", 
                                     "PS > D > PF", "PS > (D & DO) > PF", " PS > D > DO", 
                                     "PS > PF > D", "PS > DO > (D & PF)", 
                                     "PS > D > DO", "PS > (DO & PF) > D")] <- "PS"
feat$classification[feat$comp %in% c("PF > (D & DO & PS)",
                                       "PF > (D & DO)", "PF > (D & PS)", 
                                       "PF > (DO & PS)", "PF > D",
                                       "PF > DO", "PF > PS", "PF > DO > D & PS", 
                                       "PF > DO > D & PS", "PF > DO > D & PS", 
                                      "PF > D > PS", "PF > (D & DO) > PS", "PF > DO > PS", 
                                      "PF > PS > D", "PF > PS > DO", "PF > PS > (D & DO)", "PF > (DO & PS) > D", 
                                     "PF > (D & PS) > DO", "PF > DO > D")] <- "PF"
feat$classification[feat$comp %in% c("D > (DO & PF & PS)",
                                       "D > (DO & PF)", "D > (DO & PS)", 
                                       "D > (PS & PF)", "D > PF",
                                       "D > DO", "D > PS", " D > (PF & PS)", 
                                       "D > (PF & PS)", "D > PF > PS")] <- "D"
feat$classification[feat$comp %in% c("DO > (D & PF & PS)",
                                       "DO > (D & PF)", "DO > (D & PS)", 
                                       "DO > (PS & PF)", "DO > PF",
                                       "DO > D", "DO > PS", "DO > (PF & PS)", 
                                     "DO > D > (PF & PS)", "DO > PF > PS", 
                                     "DO > PS > PF", "DO > D > PS", "DO > (D & PF) > PS", "DO > (D & PS) > PF")] <- "DO"
feat$classification[feat$comp %in% c("(D & DO) > PF","(D & DO) > (PF & PS)",
                                       "(D & DO) > PS", "(D & DO) > PF > PS", "DO > D > PF", 
                                     "(D & DO) > PS > PF", "DO > D > PF")] <- "DDO" #deterini specific
feat$classification[feat$comp %in% c("(DO & PF & PS) > D", "(DO & PS) > D", "(DO & PF) > D")] <- "ND" 
                                    #not detterini specific
feat$classification[feat$comp %in% c("(D & PF & PS) > DO", "(D & PF) > DO", "(D & PF) > DO & PS)")] <- "ND" 
                                    #not ORGANIC specific
feat$classification[feat$comp %in% c("(D & DO & PS) > PF", "(DO & PS) > PF", "(DO & PS) > (D & PF)",
                                     "(D & PS) > PF", "DO > (D & PS) > PF")] <- "NPF" #not PF specific
feat$classification[feat$comp %in% c("(D & DO & PF) > PS", "(DO & PF) > PS", "(D & DO & PF) > PS", 
                                     "(DO & PF) > (D & PS)", "(DO & PF) > D > PS", 
                                    "(D & PF) > PS", "(D & PF) > DO & PS)")] <- "NPS" #not PS specific

feat$classification[feat$comp %in% c("(PF & PS) > DO", "(PF & PS) > D", "PS > PF > D & DO", 
                                       "(PF & PS) > DO > D", "(PF & PS) > (D & DO)")] <- "PSPF"
#In some cases also two classes could be assigned, could be specific or not specific for two groups
unique(feat$comp[feat$classification == "x"])
```

# Annotation

## Features of STDS

```{r annotation-std}
load("rdata/ionsdb_stds.RData")
if(p == "POS"){
  ionsdb <- ionsdb[ionsdb$ion_adduct == "[M+H]+",]
} else if(p == "NEG"){
  ionsdb <- ionsdb[ionsdb$ion_adduct == "[M-H]-",]
}

pr <- MzRtParam(tolerance = 0.01, toleranceRt = 0.2) # define the parameters
mt_ft <- matchValues(feat, ionsdb, param = pr, 
                     rtColname = c("RT", "ion_rt"),
                     mzColname = c("mz", "ion_mz"))
mtft_df <- data.frame(matchedData(mt_ft))
ft_stds <- mtft_df[!is.na(mtft_df$target_name),]
ft_na <- mtft_df[is.na(mtft_df$target_name),]
```


## MS2 annotated features

```{r}
load("rdata/ionsdb_MS2_ann.RData")
if(p == "POS"){
  ionsdb <- ionsdb[ionsdb$ion_adduct == "[M+H]+",]
} else if(p == "NEG"){
  ionsdb <- ionsdb[ionsdb$ion_adduct == "[M-H]-",]
}

pr <- MzRtParam(tolerance = 0.01, toleranceRt = 0.15) # define the parameters
mt_ft <- matchValues(ft_na[,1:(grep("target_", colnames(ft_na))[1]-1)], 
                     ionsdb, param = pr, 
                     rtColname = c("RT", "ion_rt"),
                     mzColname = c("mz", "ion_mz"))
mtft_df <- data.frame(matchedData(mt_ft))
ft_ms2 <- mtft_df[!is.na(mtft_df$target_name),]
ft_na <- mtft_df[is.na(mtft_df$target_name),]
```



## Annotation using suspect list

```{r annotation-sl}
load("rdata/ionsdb_SL.RData")
if(p == "POS"){
  ionsdb <- ionsdb[ionsdb$ion_adduct == "[M+H]+",]
} else if(p == "NEG"){
  ionsdb <- ionsdb[ionsdb$ion_adduct == "[M-H]-",]
}

pr <- MzParam(tolerance = 0.01) # define the parameters
mt_ft <- matchValues(ft_na[,1:(grep("target_", colnames(ft_na))[1]-1)], 
                     ionsdb, param = pr, 
                     mzColname = c("mz", "ion_mz"))
mtft_df <- data.frame(matchedData(mt_ft))

ft_sl <- mtft_df[!is.na(mtft_df$target_name),]
```



# Annotated compounds

```{r annotations1}
ft_stds$mz <- round(ft_stds$mz, 4)
ft_stds$RT <- round(ft_stds$RT, 2)
ft_stds$dev_mDa <- round(ft_stds$score*1000, 1)
ft_stds$max <- round(ft_stds$max)
datatable(ft_stds[,c("FT", "mz", "RT", "target_name", "dev_mDa", "comp",
                     "target_activity", "target_comment",
                     "target_level", "target_abc", "target_mode",  
                     "max", "max_class")])


ft_ms2$mz <- round(ft_ms2$mz, 4)
ft_ms2$RT <- round(ft_ms2$RT, 2)
ft_ms2$dev_mDa <- round(ft_ms2$score*1000, 1)
ft_ms2$max <- round(ft_ms2$max)
datatable(ft_ms2[,c("FT", "mz", "RT", "target_name", "dev_mDa", "comp", 
                    "target_activity", "target_comment",
                     "target_level", "target_abc", "target_mode",  
                     "max", "max_class")])


print(length(unique(ft_sl$FT)))
ft_sl$mz <- round(ft_sl$mz, 4)
ft_sl$target_ion_mz <- round(ft_sl$target_ion_mz, 4)
ft_sl$RT <- round(ft_sl$RT, 2)
ft_sl$dev_mDa <- round(ft_sl$score*1000, 1)
ft_sl$max <- round(ft_sl$max)

ft_sl$col <- ft_sl$FT %in% unique(ft_sl$FT[duplicated(ft_sl$FT)])
ft_sl$color <- c("white")
tmp <- unique(ft_sl$FT[duplicated(ft_sl$FT)])
tmp_col <- brewer.pal(9 , "Set1")
j <- rep(seq(9), length(tmp)/8)[1:length(tmp)]
for(i in seq(length(tmp))){
  idx <- which(ft_sl$FT == tmp[i])
  ft_sl$color[idx] <- tmp_col[j[i]]
}

#table(ft_sl$comp)
#ft_sl <- ft_sl[order(ft_sl$comp, -ft_sl$max),]
ft_sl <- ft_sl[order(ft_sl$max, decreasing = T),]
tmp_class <- unique(ft_sl$classification)
```


```{r annotations2, results='asis'}
print(htmltools::tagList(datatable(ft_sl[1,1:2])))
for(i in seq(length(tmp_class))){
  tmp_ft <- ft_sl[ft_sl$classification == tmp_class[i],]
  print(htmltools::tagList((
    DT::datatable(
      tmp_ft[,c("FT", "mz", "RT", "target_name", "target_ion_mz", "dev_mDa", "comp", 
                "target_activity", "target_comment",
                "max", "max_class", "col")]) %>% formatStyle(
                  "col",
                  target = 'row',
                  backgroundColor = styleEqual(c(FALSE, TRUE), c('white', "#E41A1C50"))
                )
  )))
}
```


# Some plots of annotated compounds

## Summary

```{r summary}
ft_ids <- rbind(ft_stds,ft_ms2)
par(mfrow = c(1, 2))
barplot(table(ft_ids$classification))
barplot(table(ft_ids$target_activity))

par(mfrow = c(1, 1))
barplot(table(ft_ids$classification, ft_ids$target_activity))
table(ft_ids$classification, ft_ids$target_activity)

par(mfrow = c(1, 1))
barplot(table(ft_ids$target_activity, ft_ids$classification))
table(ft_ids$target_activity, ft_ids$classification)
```


## Standards

```{r plot-stds}
col_class <- brewer.pal(7, "Set1")[-6]
names(col_class) <- c("D", #red
                      "QC", # blue
                      "DO", # green
                      "PF", #purple
                      "PS", # orange
                      "PPB" # brown
)



set.seed(1234)
rnd <- runif(nrow(md), -0.2, 0.2)

tmp_dt <- data_t[, colnames(data_t) %in% ft_stds$FT]

par(mfrow = c(1, 2))
for(i in seq(nrow(ft_stds))){
  idx <- which(ft_stds$FT == colnames(tmp_dt)[i])
  plot(as.numeric(md$class) + rnd, tmp_dt[,i], bty = "l",
       xlab = "class", ylab = "intensity", xaxt = "n", 
       col = col_class[as.character(md$class)], pch = 16, cex = 0.5, 
       main =  paste(ft_stds$target_name[idx],
                     "\n", round(ft_stds$mz[idx], 4), "@", round(ft_stds$RT[idx], 2),
                     "\n", ft_stds$comp[i]
       )
  )
  idx <- which(md$id %in% mdx$id)
  points(as.numeric(md$class)[idx] + rnd[idx], tmp_dt[idx,i], pch = 16,
         col = col_class[as.character(md$class)][idx])
  points(as.numeric(md$class)[idx] + rnd[idx], tmp_dt[idx,i], pch = 8,
         col = col_class[as.character(md$class)][idx])
  axis(1, at = seq(nlevels(md$class)),
       labels = levels(md$class))
}
```



## MS2 annotated compounds

```{r plot-ms2}
if(nrow(ft_ms2) == 1){
  tmp_dt <- data.frame(matrix(
    data_t[, colnames(data_t) %in% ft_ms2$FT], ncol = 1))
  colnames(tmp_dt) <- ft_ms2$FT
  rownames(tmp_dt) <- rownames(data_t)
} else {
  tmp_dt <- data_t[, colnames(data_t) %in% ft_ms2$FT]
}

if(nrow(ft_ms2) != ncol(tmp_dt)){
  print("Warning!!! There are duplicates in the annotation!!")
  datatable(ft_ms2[ft_ms2$FT %in% ft_ms2$FT[duplicated(ft_ms2$FT)],])
}


par(mfrow = c(1, 2))
for(i in seq(nrow(ft_ms2))){
  idx <- which(colnames(tmp_dt) == ft_ms2$FT[i])
  plot(as.numeric(md$class) + rnd, tmp_dt[,idx], bty = "l",
       xlab = "class", ylab = "intensity", xaxt = "n", 
       col = col_class[as.character(md$class)], pch = 16, cex = 0.5, 
       main =  paste(ft_ms2$target_name[i],
                     "\n", round(ft_ms2$mz[i], 4), "@", round(ft_ms2$RT[i], 2),
                     "\n", ft_ms2$comp[i]
       )
  )
  idx2 <- which(md$id %in% mdx$id)
  points(as.numeric(md$class)[idx2] + rnd[idx2], tmp_dt[idx2,idx], pch = 16,
         col = col_class[as.character(md$class)][idx2])
  points(as.numeric(md$class)[idx2] + rnd[idx2], tmp_dt[idx2,idx], pch = 8,
         col = col_class[as.character(md$class)][idx2])
  axis(1, at = seq(nlevels(md$class)),
       labels = levels(md$class))
}
```

## Suspect List

```{r plot-sl}
tmp_dt <- data_t[, colnames(data_t) %in% ft_sl$FT]

tmp_ft <- unique(ft_sl$FT)

par(mfrow = c(1, 2))
for(i in seq(20)){
  idx <- which(ft_sl$FT == tmp_ft[i])
  plot(as.numeric(md$class) + rnd, tmp_dt[,tmp_ft[i]], bty = "l",
       xlab = "class", ylab = "intensity", xaxt = "n", 
       col = col_class[as.character(md$class)], pch = 16, cex = 0.5, 
       main =  paste(paste(ft_sl$target_name[idx], collapse = "; "),
                     "\n", round(ft_sl$mz[idx[1]], 4), "@", round(ft_sl$RT[idx[1]], 2),
                     "\n", ft_sl$comp[i[1]]
       )
  )
  idx <- which(md$id %in% mdx$id)
  points(as.numeric(md$class)[idx] + rnd[idx], tmp_dt[idx,tmp_ft[i]], pch = 16,
         col = col_class[as.character(md$class)][idx])
  points(as.numeric(md$class)[idx] + rnd[idx], tmp_dt[idx,tmp_ft[i]], pch = 8,
         col = col_class[as.character(md$class)][idx])
  axis(1, at = seq(nlevels(md$class)),
       labels = levels(md$class))
}
```


# Session info

```{r session-info}
Sys.time()-startpoint
devtools::session_info()
```

