---
title: "Data Analysis"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```


# Libraries

```{r}
p <- "POS"
software <- "progenesis" #progenesis / mzmine
myfile <- "data/ANA_MSE_POS_ALL_MASS_PROG.xlsx" #"data/ANA_MSE_POS_MZMINE_30ppm.xlsx" #"data/ANA_MSE_POS_ALL_MASS_PROG.xlsx"

library(readxl)
library(tidyverse)
library(plotly)
library(MetaboAnnotation)
library(effectsize)
library(DT)
library(kableExtra)

scaling.pareto <- function(x){(x - mean(x)) / sqrt(sd(x))}
```


# Data import

```{r, message=FALSE}
if(software == "progenesis"){
  feat <- read_xlsx(myfile, skip = 2) #SKIP first two empty rows 
  
  tmp <- read_xlsx(myfile)
  
  # select raw data:
  data_raw <- feat[, grep("Raw", colnames(tmp)):(grep("Not identified", tmp[2,])-1)]
  
  feat <- data.frame(feat[,c(3, 5)])
  colnames(feat) <- c("mz", "RT")
  
  rm(tmp)
} else if(software == "mzmine"){
  feat <- read_xlsx(myfile) 
  
  data_raw <- feat[,4:ncol(feat)]
  feat <- data.frame(feat[,c(2, 3)])
  colnames(feat) <- c("mz", "RT")
}
feat$FT <- paste0(
  "FT", formatC(seq(nrow(feat)), width = nchar(nrow(feat)), flag = "0"))
rownames(data_raw) <- feat$FT
data_raw <- data.frame(t(data_raw))
```

# Feature quality

```{r}
smpl_class <- rep("sample", nrow(data_raw)) #replicates numeric values/text, or the values of a vector for a specific number of times
smpl_class[grep("QC", rownames(data_raw))] <- "QC" #used to search for matches of a pattern within each element of the given string
smpl_class[grep("Blank|PPB", rownames(data_raw))] <- "blank"

idx <- which(smpl_class == "blank")
feat$mean_blank <- apply(data_raw[idx,], 2, mean) #apply() takes Data frame or matrix as an input and gives output in vector
idx <- which(smpl_class == "sample")
feat$mean_samples <- apply(data_raw[idx,], 2, mean)
feat$mean_ratio <- feat$mean_samples / feat$mean_blank #

rsd <- function(x){(sd(x) / mean(x))*100} #For mass features rsd higher in the qc than in the samples excluded them
idx <- which(smpl_class == "QC")
feat$RSD_QC <- apply(data_raw[idx,], 2, rsd)
idx <- which(smpl_class == "sample")
feat$RSD_samples <- apply(data_raw[idx,], 2, rsd) #change feat, and make a dataframe of normalised data called sth and replace the data_raw, and move down, check what is happing! 

# number of NON-missing values in QC
idx_QC <- grep("QC", rownames(data_raw))
smpl_order <- as.numeric(substr(rownames(data_raw), 13, 14))
idx_QC <- idx_QC[(smpl_order[idx_QC] >= 8) & (smpl_order[idx_QC] <= 59)] #take only qc from the last of the first and the first of the last
data_QC <- data_raw[idx_QC, ]
feat$QC_nonNA <- apply(data_QC, 2, function(x) sum(x > 0)) #in how many samples the feature is not zero, missing?

feat$noise <- (feat$mean_ratio < 5) | (feat$RSD_QC > feat$RSD_samples) | 
  (feat$QC_nonNA < max(feat$QC_nonNA)*0.75) |
  (feat$mean_blank == 0 & feat$mean_samples == 0) #Noise if the mean ratio is bellowed 5 or rsd is higher in qc than in samples or feature is zero in sample and blank, is not present in more than 75% of QC

table(feat$noise)
rm(idx, idx_QC, data_QC, smpl_order) 
```


# Annotation
#implemente the annotated compounds into the code, run the iondb

## MS2 annotated features

```{r}
load("rdata/ionsdb_AnnComp.RData")
if(p == "POS"){
  ionsdb <- ionsdb[ionsdb$ion_adduct == "[M+H]+",]
} else if(p == "NEG"){
  ionsdb <- ionsdb[ionsdb$ion_adduct == "[M-H]-",]
}

pr <- MzRtParam(tolerance = 0.01, toleranceRt = 0.15) # define the parameters
mt_ft <- matchValues(feat, ionsdb, param = pr, 
                     rtColname = c("RT", "ion_rt"),
                     mzColname = c("mz", "ion_mz"))
mtft_df <- data.frame(matchedData(mt_ft))


tmp_ft <- unique(mtft_df$FT[which(duplicated(mtft_df$FT))])
for(i in seq(length(tmp_ft))){
  idx2 <- which(mtft_df$FT == tmp_ft[i],)
  tmp <- mtft_df[idx2,]
  mtft_df <- mtft_df[-idx2,]
  if(length(unique(gsub("\\ \\(.*", "", tmp$target_name))) == 1){
    tmp <- tmp[which.min(tmp$score_rt),]
  } else {
    tmp$target_name <- paste(tmp$target_name, collapse = "; ")
    tmp$target_compound_id <- tmp$target_ion_adduct <- tmp$target_ion_mz <- tmp$target_ion_rt <- tmp$target_comment <- tmp$target_activity <- tmp$target_level <- NA
    tmp <- tmp[1,]
  }
  mtft_df <- rbind(mtft_df, tmp)
}

#ft_ms2 <- mtft_df[!is.na(mtft_df$target_name),]
#ft_na <- mtft_df[is.na(mtft_df$target_name),]
```

# Data organization

```{r}
metadata <- data.frame(
  id = gsub(".*_AK_|_MSe.*", "", rownames(data_raw)) #id is the sample name, exlcude everything from _ak and after ?mse
) #we are using tidevrsy because the variables can be different and not only numeric like should be in dataframe
metadata$order <- as.numeric(gsub("_.*", "", metadata$id)) # second colum order of samples
metadata$class <- smpl_class #third colume is sample class

mydat <- cbind.data.frame(metadata, data_raw) #we have bind now the metadata with raw data

colnames(mtft_df)[colnames(mtft_df) == "FT"] <- "name" #colums in feat containing FT call the column "name"
mydat <- mydat %>%
  as.tibble() %>% # transform the object to a "tibble" 
  # each row of the tibble corresponds to a compound:
  pivot_longer(starts_with("FT"))  %>% 
  # put all columns, except "name", in the list of the tibble called "data"
  nest(data = !c("name")) %>% #this information will be in gather in one column - called data
  # aggregate feature information
  left_join(mtft_df, by = "name")  #information on id, order, class,value - raw
rm(data_raw, feat, metadata, smpl_class)

mydat <- mydat %>%
  mutate(data = map(data, function(t){ # add the column in mydat in data map with the function t applied 
    t$val_0 <- t$value
    t$value[t$value == 0] <- NA #replace zero with missing value
    t$log <- log10(t$value) #transform the t_value, log10 of na return NA
    t
  }))
```


# Normalize

```{r}
mydat <- mydat %>% #we decide not to impute data before normalisation 
  mutate(norm_mdl = map(data, function(t){
    t <- t %>%
      filter(class == "QC" & order >= 8 & order <= 59) #for normalisation we use the last of the first qc in between and the one before last one
    if(sum(is.na(t$log)) < nrow(t)*3/4){ #if feature not missing in more than 75% samples than apply the function?
      val <- t$log #we transform data before normalisation
      order <- t$order
      mdl <- lm(val ~ order) #we apply the linear normalisation on the values withing the order of injection
      mdl
    }
  }))

myimputer <- function(v, w){
  set.seed(123) #change the missing values with the random value between min value of the colume/10
  if(sum(is.na(v)) == 0){
    return(v)
  } else {
    napos <- which(is.na(v))
    newval <- runif(length(napos), 0, min(w, na.rm = TRUE)/10)
    out <- v
    out[napos] <- log10(newval) #tranform the new data
    return(out)
  }
}
mydat <- mydat %>% #normalise by using the individual slope exluding the missing values
  mutate(data = map2(data, norm_mdl, function(t, u){ #map function  iterate over two arguments at a time, norm mdl to have a value and not a list
    if(!is.null(u)){
      p <- predict(u, newdata = data.frame(order = t$order)) #we predict the new values based on the qc normalisation
      t$norm_indiv <- t$log - p + (u$fitted.values[1] + u$residuals[1]) #normalise predicted values by individual slope, trasformed data - fitted values plus residuals
      t$norm_indiv_i <- myimputer(v = t$norm_indiv, w = t$value) #normalise the imputed data
      t
    } else {
      t
    }
  })) 
```


# PCA

## All samples

```{r}
data <- mydat %>%
  select(c("name", "data", "noise", "target_name")) %>%
  filter(noise == FALSE) %>% #exclude noise
  filter(!is.na(target_name)) %>% #in case you don't want to only with annotated mass features than uncomment or actually coppy all the pca to have both as well as for volcano plots
  select(c("name", "data"))  %>%
  unnest(data) %>% #AGAIN BIG TABLE
  select(c("name", "id", "norm_indiv_i")) %>%
  pivot_wider(names_from = "name", values_from = "norm_indiv_i") %>% #TAKE NAME from column name and value from norm_indiv_i
  column_to_rownames("id")

data <- apply(data, 2, scaling.pareto) #apply scaling to all colums

pca <- prcomp(data, center = FALSE, scale. = FALSE)
pca_s <- data.frame(pca$x)
s_class <- mydat$data[[1]]$class
plot_ly(data = pca_s, x = ~PC1, y = ~PC2, color = s_class, colors = "Set1",
        text = rownames(data)) %>%
  layout(title = "Score plot",
         xaxis = list(title = paste0(
           "PC1 (", sprintf("%.1f", summary(pca)$importance[2,1]*100), "%)")),
         yaxis = list(title = paste0(
           "PC2 (", sprintf("%.1f", summary(pca)$importance[2,2]*100), "%)"))
  )
```


## Study samples

```{r}
mydat <- mydat %>%
  mutate(data2 = map(data, function(t){
    t$exclude <- grepl("P_|QC|PPB", t$id) # exclude blanks, pooled sampels and qc
    t <- t %>%
      filter(!t$exclude)
    t
  }))


data <- mydat %>%
  select(c("name", "data2", "noise", "target_name")) %>%
  filter(noise == FALSE) %>%
  filter(!is.na(target_name)) %>% 
  select(c("name", "data2"))  %>%
  unnest(data2) %>%
  select(c("name", "id", "norm_indiv_i")) %>%
  pivot_wider(names_from = "name", values_from = "norm_indiv_i") %>%
  column_to_rownames("id")

data <- apply(data, 2, scaling.pareto)

pca <- prcomp(data, center = FALSE, scale. = FALSE)
pca_s <- data.frame(pca$x)

s_class <- gsub('[[:digit:]]+', '', rownames(data)) #exlude numbers from the names, we had to do it like that because i made some errors in sample names
s_class <- gsub("_", "", s_class)

plot_ly(data = pca_s, x = ~PC1, y = ~PC2, color = s_class, colors = "Set2", size = 2,
        text = rownames(data)) %>%
  layout(title = "Score plot",
         xaxis = list(title = paste0(
           "PC1 (", sprintf("%.1f", summary(pca)$importance[2,1]*100), "%)")),
         yaxis = list(title = paste0(
           "PC2 (", sprintf("%.1f", summary(pca)$importance[2,2]*100), "%)"))
  )

plot_ly(data = pca_s, x = ~PC3, y = ~PC4, color = s_class, colors = "Set2", size = 2,
        text = rownames(data)) %>%
  layout(title = "Score plot",
         xaxis = list(title = paste0(
           "PC3 (", sprintf("%.1f", summary(pca)$importance[2,3]*100), "%)")),
         yaxis = list(title = paste0(
           "PC4 (", sprintf("%.1f", summary(pca)$importance[2,4]*100), "%)"))
  )
```


# Pairwise comparision

```{r}
mydat <- mydat %>%
  mutate(data2 = map(data2, function(t){
    t$class <- gsub('[[:digit:]]+', '', t$id)
    t$class <- gsub("_", "", t$class)
    t
  }))
```


## PS vs others

```{r}
mydat <- mydat %>%
  #  filter(noise == FALSE) %>% 
  mutate(pval_PS = map2_dbl(data2, noise, function(t, u){ #mutate or addd colume with p value for feature not noise and 9 for feature that is noise
    if(u == FALSE){
      t$group <- ifelse(t$class == "PS", "PS", "others") #if ps than named ps otherwise others, group colume is others and ps
      t.test(t$norm_indiv_i ~ t$group)$p.value #perform t test using value norm_indiv_i between two groups in colume group
    } else {
      9
    }
  })) %>%
  mutate(es_PS = map2_dbl(data2, noise, function(t, u){ #calculating the effect size in the same way
    if(u == FALSE){
      t$group <- ifelse(t$class == "PS", "PS", "others")
      cohens_d(t$norm_indiv_i ~ t$group)$Cohens_d #if not noise calculate the cohens_d otherwise put zero, the higher the cohens_d the higher significance 
    } else {
      0
    }
  }))

#make volcano plots 
idx <- which(!mydat$noise & !is.na(mydat$target_name)) #data that is not noise
plot(mydat$es_PS[idx], -log10(mydat$pval_PS)[idx], bty = "l", #apply -log10 on p values, bty = "l" - cosumaying the box around the plot
     xlab = "Cohens'd", ylab = "-log10(p-value)", main = "PS vs others",
     xlim = max(abs(mydat$es_PS[idx])) * c(-1, 1)) #we centrilised the zero values
#abline(h = -log10(0.05), col = "grey", lty = 2)
idx <- which(mydat$noise == FALSE & !is.na(mydat$target_name) & mydat$pval_PS < 0.0001 & mydat$es_PS < (-10)) #define some criterias for significan mass features, my data is not noise, pvalue higher than 0.0001 and ef lower than  -10
points(mydat$es_PS[idx], -log10(mydat$pval_PS)[idx], col = "#E78AC360", pch = 16)
idx <- which(mydat$noise == FALSE & !is.na(mydat$target_name) & mydat$pval_PS < 0.0001 & mydat$es_PS > 10)
points(mydat$es_PS[idx], -log10(mydat$pval_PS)[idx], col = "#A6D85460", pch = 16)
```


## PF vs (D & DO)

```{r}
mydat <- mydat %>%
  #  filter(noise == FALSE) %>%
  mutate(pval_PF = map2_dbl(data2, noise, function(t, u){
    if(u == FALSE){
      t <- t %>%
        filter(class != "PS") #exclude PS group
      t$group <- ifelse(t$class == "PF", "PF", "others")
      t.test(t$norm_indiv_i ~ t$group)$p.value
    } else {
      9
    }
  })) %>%
  mutate(es_PF = map2_dbl(data2, noise, function(t, u){
    if(u == FALSE){
      t <- t %>%
        filter(class != "PS")
      t$group <- ifelse(t$class == "PF", "PF", "others")
      cohens_d(t$norm_indiv_i ~ t$group)$Cohens_d
    } else {
      0
    }
  }))
#make volcano plots 
idx <- which(!mydat$noise) #data that is not noise
plot(mydat$es_PF[idx], -log10(mydat$pval_PF)[idx], bty = "l", #apply -log10 on p values, bty = "l" - cosumaying the box around the plot
     xlab = "Cohens'd", ylab = "-log10(p-value)", main = "PF vs others",
     xlim = max(abs(mydat$es_PF[idx])) * c(-1, 1)) #we centrilised the zero values
#abline(h = -log10(0.05), col = "grey", lty = 2)
idx <- which(mydat$noise == FALSE & mydat$pval_PF < 0.001 & mydat$es_PF < (-3.5)) #define some criterias for significan mass features, my data is not noise, pvalue higher than 0.0001 and ef lower than absolute -10
points(mydat$es_PF[idx], -log10(mydat$pval_PF)[idx], col = "#E78AC360", pch = 16)
idx <- which(mydat$noise == FALSE & mydat$pval_PF < 0.001 & mydat$es_PF > 7)
points(mydat$es_PF[idx], -log10(mydat$pval_PF)[idx], col = "#A6D85460", pch = 16)
```


## D vs DO

```{r}
mydat <- mydat %>%
  #  filter(noise == FALSE) %>%
  mutate(pval_D = map2_dbl(data2, noise, function(t, u){
    if(u == FALSE){
      t <- t %>%
        filter(class != "PS|PF") #exclude PS and PF group
      t$group <- ifelse(t$class == "D", "D", "DO")
      t.test(t$norm_indiv_i ~ t$group)$p.value
    } else {
      9
    }
  })) %>%
  mutate(es_D = map2_dbl(data2, noise, function(t, u){
    if(u == FALSE){
      t <- t %>%
        filter(class != "PS|PF")
      t$group <- ifelse(t$class == "D", "D", "DO")
      cohens_d(t$norm_indiv_i ~ t$group)$Cohens_d
    } else {
      0
    }
  }))
#make volcano plots 
idx <- which(!mydat$noise) #data that is not noise
plot(mydat$es_D[idx], -log10(mydat$pval_D)[idx], bty = "l", #apply -log10 on p values, bty = "l" - cosumaying the box around the plot
     xlab = "Cohens'd", ylab = "-log10(p-value)", main = "D vs DO",
     xlim = max(abs(mydat$es_D[idx])) * c(-1, 1)) #we centrilised the zero values
#abline(h = -log10(0.05), col = "grey", lty = 2)
idx <- which(mydat$noise == FALSE & mydat$pval_D < 0.05 & mydat$es_D < (-1.9)) #define some criterias for significan mass features, my data is not noise, pvalue higher than 0.0001 and ef lower than absolute -10
points(mydat$es_D[idx], -log10(mydat$pval_D)[idx], col = "#E78AC360", pch = 16)
idx <- which(mydat$noise == FALSE & mydat$pval_D < 0.001 & mydat$es_D > 1.9)
points(mydat$es_D[idx], -log10(mydat$pval_D)[idx], col = "#A6D85460", pch = 16)
```

# Session information

```{r session}
Sys.time()-startpoint
#devtools::session_info()
```